# Generated by Django 3.0.6 on 2020-06-10 13:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_off', '0004_product_nutrition_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purbeurre_favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'favorite')},
        ),
    ]
