# Generated by Django 3.0.5 on 2020-05-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_off', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('link', 'category')},
        ),
    ]
