# Generated by Django 3.0.6 on 2020-05-20 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_off', '0002_auto_20200513_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
