# Generated by Django 3.0.6 on 2020-06-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre_off', '0003_auto_20200520_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nutrition_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
